name: Build Web

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@main
        with:
          node-version: 18

      - name: Build System Setup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get install -y squashfs-tools jq
          sudo apt-get install -y dos2unix
          sudo npm install -g pnpm
          sudo npm i taze -g

      - name: Update Makefile
        id: update_makefile
        run: |
          chmod 755 ./dae/files/dae.init
          find ./ -type f -exec dos2unix {} \; -print
          latest_commit_info="$(curl -s https://api.github.com/repos/olicesx/dae/commits/optimize/code-quality-fixes)"
          latest_commit_full="$(echo "$latest_commit_info" | jq -r '.sha')"
          current_commit_full=$(grep 'PKG_SOURCE_VERSION:=' ./dae/Makefile | cut -d '=' -f 2)
          
          if [ "$current_commit_full" = "$latest_commit_full" ]; then
            echo "Upstream is already up-to-date ($current_commit_full)."
            echo "updated=false" >> "$GITHUB_ENV"
          else
            latest_commit="$(echo $latest_commit_full | cut -b 1-7)"
            latest_core_date="$(echo "$latest_commit_info" | jq -r '.commit.committer.date | split("T")[0] | split("-") | "\(.[0]).\(.[1]).\(.[2])"')"
            timestamp=$(echo "$latest_commit_info" | jq -r '.commit.author.date')
            formatted_timestamp=$(date --date="$timestamp" "+%Y-%m-%d")
            
            sed -i "s/^PKG_VERSION:=.*/PKG_VERSION:=$latest_core_date/" ./dae/Makefile
            sed -i "s/^PKG_SOURCE_VERSION:=.*/PKG_SOURCE_VERSION:=$latest_commit_full/" ./dae/Makefile
            
            echo "version=$formatted_timestamp-$latest_commit" >> "$GITHUB_ENV"
            echo "updated=true" >> "$GITHUB_ENV"
          fi

      - name: Commit file
        if: env.updated == 'true'
        run: |
          rm -rf build
          git config --global user.email simonsqiu@foxmail.com
          git config --global user.name SimonsQiu
          git add .
          git commit -m "Update `date +%Y/%m/%d\ %H:%M:%S\ %Z`" -a
        continue-on-error: true

      - name: Push changes
        if: env.updated == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.ACTIONS_DEPLOY_KEY}}
          branch: kix
        continue-on-error: true

      - name: Cleanup Workflow Logs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{secrets.ACTIONS_DEPLOY_KEY}}
          repository: ${{ github.repository }}
          retain_days: 1
        continue-on-error: true

      - name: Delete Older Releases
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{secrets.ACTIONS_DEPLOY_KEY}}
        continue-on-error: true

      - name: Cleanup Old Action Artifacts
        uses: c-hive/gha-remove-artifacts@master
        with:
          age: '3 days'
          skip-recent: 3
        continue-on-error: true

      - name: Cleanup Workflow Logs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{secrets.ACTIONS_DEPLOY_KEY}}
          repository: ${{ github.repository }}
          retain_days: 3
        continue-on-error: true
